### ISSUE TITLE
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `[Lcom.appium.device.Device;` from Object value (token `JsonToken.START_OBJECT`)  at [Source: (String)"{"status":9,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":""}}"; line: 1, column: 1]

### ISSUE THREAD

**Issue by xiaoliangjia111** [AppiumTestDistribution/DeviceManager#70]
There was a problem with the equipment farm not starting after the program was packaged

CS001deMac-mini:target root# java -jar PagePatternAppium-0.0.1-SNAPSHOT-assembly.jar
log4j:WARN No appenders could be found for logger (com.appium.utils.ConfigFileManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
[Appium] Welcome to Appium v2.0.0-beta.71
[Appium] Non-default server args:
[Appium] { address: '127.0.0.1',
[Appium]   basePath: '/wd/hub/',
[Appium]   port: 12982,
[Appium]   relaxedSecurityEnabled: true,
[Appium]   usePlugins: [ 'device-farm' ] }
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at /private/var/root/.appium/node_modules/appium-uiautomator2-driver
[Appium] Appium REST http interface listener started on 127.0.0.1:12982/wd/hub/
[Appium] Available drivers:
[Appium]   - uiautomator2@2.25.2 (automationName 'UiAutomator2')
[Appium] Available plugins:
[Appium]   - appium-dashboard@v2.0.2
[Appium] No plugins activated. Use the --use-plugins flag with names of plugins to activate
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [AppiumDriver@4172] Calling AppiumDriver.getStatus() with args: []
[debug] [AppiumDriver@4172] Responding to client with driver.getStatus() result: {"build":{"version":"2.0.0-beta.71"}}
[HTTP] <-- GET /wd/hub/status 200 4 ms - 47
[HTTP] 
1
[HTTP] --> GET /device-farm/api/devices
[HTTP] {}
[debug] [HTTP] No route found for /device-farm/api/devices
[HTTP] <-- GET /device-farm/api/devices 404 8 ms - 211
[HTTP] 
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `[Lcom.appium.device.Device;` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (String)"{"status":9,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":""}}"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1746)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1520)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1467)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.handleNonArray(ObjectArrayDeserializer.java:345)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
	at com.appium.device.Devices.getConnectedDevices(Devices.java:28)
	at com.appium.manager.ATDRunner.<init>(ATDRunner.java:40)
	at com.appium.tests.RunnerParaller.testRunner(RunnerParaller.java:14)
	at com.appium.tests.RunnerParaller.main(RunnerParaller.java:26)

**Comment by saikrishna321** [comment]
plug-in is not active. Make sure Appium-device farm plugin is active

**Comment by xiaoliangjia111** [comment]
> 插件未激活。确保 Appium 设备场插件处于活动状态

How to activate plugins and open device farms

**Comment by xiaoliangjia111** [comment]
![Uploading 企业微信截图_427e90ae-6c14-4942-8346-513e7a9254e6.png…]()

**Comment by saikrishna321** [comment]
Have u installed device-farm
Plugin? 

Show me output of 

appium plugin list

**Comment by xiaoliangjia111** [comment]
> 你安装了 device-farm 插件吗？
> 
> 显示我的输出
> 
> appium插件列表

sxw@CS001deMac-mini ~ % appium plugin list
✔ Listing available plugins
- device-farm@7.4.0 [installed (npm)]
- appium-dashboard@v2.0.2 [installed (npm)]
- appium-reporter-plugin@1.1.0-beta.01 [installed (npm)]
- images [not installed]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]

**Comment by xiaoliangjia111** [comment]
> > 你安装了 device-farm 插件吗？
> > 显示我的输出
> > appium 插件列表
> 
> sxw@CS001deMac-mini ~ % appium 插件列表 ✔ 列出可用插件
> 
> * device-farm@7.4.0 [已安装 (npm)]
> * appium-dashboard@v2.0.2 [已安装 (npm)]
> * appium-reporter-plugin@1.1.0-beta.01 [已安装 (npm)]
> * 图片[未安装]
> * 执行驱动程序[未安装]
> * relaxed-caps [未安装]
> * Universal-xml [未安装]

was installed

**Comment by saikrishna321** [comment]
@xiaoliangjia111 Can you show me your caps.json file ?
